//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfmtest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalProjectEntities : DbContext
    {
        public HospitalProjectEntities()
            : base("name=HospitalProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Announcements> Tbl_Announcements { get; set; }
        public virtual DbSet<Tbl_Doctors> Tbl_Doctors { get; set; }
        public virtual DbSet<Tbl_Patients> Tbl_Patients { get; set; }
        public virtual DbSet<Tbl_Secretary> Tbl_Secretary { get; set; }
        public virtual DbSet<Tbl_branch> Tbl_branch { get; set; }
        public virtual DbSet<Table1> Table1 { get; set; }
        public virtual DbSet<Tbl_Appointments> Tbl_Appointments { get; set; }
    }
}
