//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfmtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Secretary
    {
        public byte secid { get; set; }
        public string secnamesurname { get; set; }
        public string sectc { get; set; }
        public string secpassword { get; set; }
    }
}
