//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfmtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Announcements
    {
        public short announcementid { get; set; }
        public string announcement { get; set; }
    }
}
