//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfmtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patients
    {
        public short patientid { get; set; }
        public string patientname { get; set; }
        public string patientsurname { get; set; }
        public string patienttc { get; set; }
        public string patienttel { get; set; }
        public string patientpassword { get; set; }
        public string patientgender { get; set; }
    }
}
