//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfmtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Doctors()
        {
            this.Tbl_Appointments = new HashSet<Tbl_Appointments>();
        }
    
        public int docid { get; set; }
        public string docname { get; set; }
        public string docsurname { get; set; }
        public string docbranch { get; set; }
        public string doctc { get; set; }
        public string docpassword { get; set; }
    
        public virtual Tbl_Doctors Tbl_Doctors1 { get; set; }
        public virtual Tbl_Doctors Tbl_Doctors2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Appointments> Tbl_Appointments { get; set; }
    }
}
